// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gpbjoNFhsd3hKmLAEF0_AWjKacPJKM8',
    appId: '1:545013436588:web:e72ce177284d37124c4f09',
    messagingSenderId: '545013436588',
    projectId: 'dinamit-14312',
    authDomain: 'dinamit-14312.firebaseapp.com',
    storageBucket: 'dinamit-14312.firebasestorage.app',
    measurementId: 'G-M3NSVRVF2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVzOeBdrAtjnP2HX1Cx0S4YkdmSWa9eM',
    appId: '1:545013436588:android:67a83434baf9a72e4c4f09',
    messagingSenderId: '545013436588',
    projectId: 'dinamit-14312',
    storageBucket: 'dinamit-14312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0JHGSAD97IvFHsfsalOtbGe5BlZiOAaU',
    appId: '1:545013436588:ios:5b8d1213a0a4e0ca4c4f09',
    messagingSenderId: '545013436588',
    projectId: 'dinamit-14312',
    storageBucket: 'dinamit-14312.firebasestorage.app',
    iosBundleId: 'com.dynamind.dinamit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0JHGSAD97IvFHsfsalOtbGe5BlZiOAaU',
    appId: '1:545013436588:ios:5b8d1213a0a4e0ca4c4f09',
    messagingSenderId: '545013436588',
    projectId: 'dinamit-14312',
    storageBucket: 'dinamit-14312.firebasestorage.app',
    iosBundleId: 'com.dynamind.dinamit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6gpbjoNFhsd3hKmLAEF0_AWjKacPJKM8',
    appId: '1:545013436588:web:024078b0e405c4f94c4f09',
    messagingSenderId: '545013436588',
    projectId: 'dinamit-14312',
    authDomain: 'dinamit-14312.firebaseapp.com',
    storageBucket: 'dinamit-14312.firebasestorage.app',
    measurementId: 'G-XRZD5XEWC4',
  );

}